name: Docker Image CI

on:
  push:
    branches: [ "release" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      
    -
      name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
      
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: 'gradle'
        
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build gradle project
      run: ./gradlew bootJar --no-daemon
    
    - name: Build Docker Image
      run: |
        DOCKER_BUILD_KIT=1 DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --push \
        -t docker.io/rootdavinalfa/demo-parking:latest \
        -t docker.io/rootdavinalfa/demo-parking:$(git rev-parse --short HEAD) \
        --platform=linux/amd64,linux/arm64 .
